import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowLeft, ArrowRight, Building2, Eye, EyeOff, GraduationCap, Landmark, LockKeyhole, Mail, ShieldCheck, UserRound } from 'lucide-react'
import { Field, Logo } from '../../components/common/UI'
import { useAuth } from '../../context/AuthContext'
import { useUser } from '../../context/UserContext'

const roles = [{key:'student',label:'Student',icon:GraduationCap},{key:'faculty',label:'Faculty',icon:Landmark},{key:'company',label:'Company',icon:Building2},{key:'admin',label:'Admin',icon:ShieldCheck}]
const homeFor = (role) => `/${role}/dashboard`

function AuthLayout({ children, heading, subheading }) { return <div className="grid min-h-screen bg-white lg:grid-cols-[.9fr_1.1fr]"><aside className="relative hidden overflow-hidden bg-navy-900 p-12 text-white lg:flex lg:flex-col"><div className="absolute inset-0 hero-grid opacity-10"/><div className="absolute -left-32 top-1/3 h-72 w-72 rounded-full bg-blue-500/30 blur-3xl"/><Link className="relative" to="/"><Logo dark/></Link><div className="relative my-auto max-w-lg"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-blue-500/20 text-blue-300"><LockKeyhole size={26}/></span><h1 className="mt-7 text-4xl font-extrabold leading-tight">One secure workspace.<br/><span className="text-blue-300">A world of opportunity.</span></h1><p className="mt-5 leading-7 text-slate-300">Connect skills, education and hiring outcomes through a trusted collaboration network.</p><div className="mt-10 grid grid-cols-3 gap-3">{[['10K+','Learners'],['500+','Campuses'],['1K+','Partners']].map(([v,l])=><div className="rounded-xl border border-white/10 bg-white/[.06] p-4" key={l}><b className="block text-xl">{v}</b><span className="text-xs text-slate-400">{l}</span></div>)}</div></div><p className="relative text-xs text-slate-500">© 2026 SkillBridge · Secure frontend demo</p></aside><main className="flex min-h-screen items-center justify-center px-4 py-10 sm:px-8"><div className="w-full max-w-lg"><div className="mb-8 flex items-center justify-between lg:hidden"><Link to="/"><Logo/></Link><Link to="/" className="btn-ghost"><ArrowLeft size={16}/>Home</Link></div><h1 className="text-3xl font-extrabold text-navy-900">{heading}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{subheading}</p>{children}</div></main></div> }

export function Login() {
  const [role,setRole]=useState('student'),[show,setShow]=useState(false),[loading,setLoading]=useState(false)
  const { login }=useAuth(),{toast}=useUser(),navigate=useNavigate()
  const go=(r=role)=>{setLoading(true);setTimeout(()=>{login(r);toast(`Welcome to your ${r} workspace`);navigate(homeFor(r))},550)}
  return <AuthLayout heading="Welcome back" subheading="Sign in to continue building stronger career outcomes."><div className="mt-7 grid grid-cols-4 gap-1 rounded-xl bg-slate-100 p-1">{roles.map(({key,label,icon:Icon})=><button key={key} onClick={()=>setRole(key)} className={`flex flex-col items-center gap-1 rounded-lg px-2 py-2 text-[11px] font-bold transition sm:flex-row sm:justify-center ${role===key?'bg-white text-brand-700 shadow-sm':'text-slate-500'}`}><Icon size={15}/>{label}</button>)}</div><form className="mt-6 space-y-4" onSubmit={e=>{e.preventDefault();go()}}><label className="block"><span className="label">Email address</span><div className="relative"><Mail className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input required type="email" defaultValue={`${role}@skillbridge.demo`} className="input pl-10"/></div></label><label className="block"><span className="label">Password</span><div className="relative"><LockKeyhole className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input required type={show?'text':'password'} defaultValue="skillbridge" className="input pl-10 pr-11"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400" aria-label="Toggle password visibility">{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label><div className="flex justify-between text-sm"><label className="flex items-center gap-2 font-medium text-slate-600"><input type="checkbox" defaultChecked className="accent-blue-600"/>Remember me</label><Link to="/forgot-password" className="font-semibold text-brand-600">Forgot password?</Link></div><button disabled={loading} className="btn-primary w-full">{loading?'Signing you in…':`Sign in as ${roles.find(x=>x.key===role).label}`}<ArrowRight size={16}/></button></form><div className="my-5 flex items-center gap-3 text-xs text-slate-400"><span className="h-px flex-1 bg-slate-200"/>or continue with<span className="h-px flex-1 bg-slate-200"/></div><div className="grid grid-cols-2 gap-3"><button onClick={()=>go()} className="btn-secondary"><span className="font-extrabold text-blue-600">G</span>Google</button><button onClick={()=>go()} className="btn-secondary"><span className="font-extrabold text-sky-700">in</span>LinkedIn</button></div><p className="mt-7 text-center text-sm text-slate-500">New to SkillBridge? <Link className="font-bold text-brand-600" to="/signup">Create an account</Link></p><div className="mt-6 rounded-xl border border-blue-100 bg-blue-50 p-3 text-center text-xs text-blue-700">Demo mode: choose any role and sign in with the prefilled credentials.</div></AuthLayout>
}

export function Signup() {
  const {login}=useAuth(),{toast}=useUser(),navigate=useNavigate()
  const select=(role)=>{login(role);toast('Demo account created successfully');navigate(homeFor(role))}
  const options=[{role:'student',icon:GraduationCap,title:'Student',text:'Find internships, jobs and grow your skills.',color:'bg-blue-50 text-blue-600'},{role:'faculty',icon:Landmark,title:'Faculty / Academia',text:'Track student progress and collaborate with industry.',color:'bg-violet-50 text-violet-600'},{role:'company',icon:Building2,title:'Industry / Company',text:'Post opportunities and hire top talent.',color:'bg-emerald-50 text-emerald-600'}]
  return <AuthLayout heading="Join the SkillBridge network" subheading="First, tell us how you want to use the platform."><div className="mt-8 space-y-3">{options.map(({role,icon:Icon,title,text,color})=><button onClick={()=>select(role)} key={role} className="group flex w-full items-center gap-4 rounded-2xl border border-slate-200 p-5 text-left transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-soft"><span className={`grid h-12 w-12 shrink-0 place-items-center rounded-xl ${color}`}><Icon size={22}/></span><span className="min-w-0 flex-1"><strong className="block text-base text-navy-900">{title}</strong><span className="mt-1 block text-sm text-slate-500">{text}</span></span><ArrowRight className="text-slate-300 transition group-hover:translate-x-1 group-hover:text-brand-600" size={19}/></button>)}</div><p className="mt-7 text-center text-sm text-slate-500">Already have an account? <Link className="font-bold text-brand-600" to="/login">Sign in</Link></p></AuthLayout>
}

export function ForgotPassword() {
  const [sent,setSent]=useState(false)
  return <AuthLayout heading={sent?'Check your inbox':'Reset your password'} subheading={sent?'We sent a secure reset link to your email address.':'Enter your account email and we’ll send you a secure reset link.'}>{sent?<div className="mt-8 rounded-2xl border border-emerald-200 bg-emerald-50 p-6 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-white text-emerald-600"><Mail/></span><p className="mt-4 text-sm text-emerald-800">The demo reset email has been sent. You can safely return to login.</p><Link to="/login" className="btn-primary mt-5">Back to login</Link></div>:<form className="mt-8 space-y-5" onSubmit={e=>{e.preventDefault();setSent(true)}}><Field required label="Email address" type="email" placeholder="you@example.com"/><button className="btn-primary w-full">Send reset link<ArrowRight size={16}/></button><Link to="/login" className="btn-ghost w-full"><ArrowLeft size={16}/>Back to login</Link></form>}</AuthLayout>
}
