import { useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, Play, Sparkles, BrainCircuit, Route, BriefcaseBusiness, Handshake, UserRound, ScanSearch, Target, Search, ChevronDown, CheckCircle2, GraduationCap, Building2, Landmark, Quote, Linkedin, Twitter, Instagram, Menu, X } from 'lucide-react'
import { Logo, Modal } from '../../components/common/UI'
import { opportunities } from '../../data/opportunities'
import { companies } from '../../data/companies'

const features = [
  { icon: BrainCircuit, title: 'Intelligent skill mapping', text: 'See how your abilities compare with the skills employers are actively hiring for.', color: 'bg-blue-50 text-blue-600' },
  { icon: Route, title: 'Personalized learning', text: 'Turn every skill gap into a practical, focused roadmap with curated resources.', color: 'bg-violet-50 text-violet-600' },
  { icon: BriefcaseBusiness, title: 'Internships & placements', text: 'Discover relevant opportunities ranked by transparent profile-match scores.', color: 'bg-emerald-50 text-emerald-600' },
  { icon: Handshake, title: 'Industry collaboration', text: 'Give institutions and employers a shared space to create career outcomes.', color: 'bg-amber-50 text-amber-600' },
]
const steps = [
  ['01','Build your profile','Bring your education, skills, projects and credentials together.'],['02','Analyze your skills','Get a clear picture of strengths and readiness.'],['03','Discover skill gaps','Compare your profile with real industry demand.'],['04','Explore opportunities','Find internships and jobs that fit your potential.'],['05','Build your career','Learn, apply and track every step to placement.'],
]
const faqs = [
  ['Who can use SkillBridge?','Students, faculty teams, accredited institutions, employers and authorized public-sector administrators each get a purpose-built workspace.'],
  ['How are opportunity matches calculated?','The demo compares profile skills, proficiency, education and career preferences with each role’s requirements to show an explainable match score.'],
  ['Is SkillBridge free for students?','Students can build a profile, analyze skills, follow a roadmap and apply to listed opportunities without a subscription in this frontend demonstration.'],
  ['Can institutions create training programs?','Yes. Faculty users can review cohort skill gaps, create workshops and track programs with industry partners.'],
]

export default function Landing() {
  const [nav, setNav] = useState(false), [demo, setDemo] = useState(false), [faq, setFaq] = useState(0)
  return <div className="min-h-screen bg-white text-slate-700">
    <header className="sticky top-0 z-40 border-b border-slate-200/70 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-4 sm:px-6"><Link to="/" aria-label="SkillBridge home"><Logo/></Link><nav className="hidden items-center gap-7 lg:flex">{['Home','About','Features','Opportunities','Institutions','Companies','Contact'].map((x) => <a key={x} href={x === 'Home' ? '#home' : `#${x.toLowerCase()}`} className="text-sm font-semibold text-slate-500 transition hover:text-brand-600">{x}</a>)}</nav><div className="hidden items-center gap-2 lg:flex"><Link to="/login" className="btn-ghost">Log in</Link><Link to="/signup" className="btn-primary">Get started<ArrowRight size={16}/></Link></div><button className="btn-ghost px-2 lg:hidden" onClick={() => setNav(!nav)} aria-label="Toggle navigation">{nav ? <X/> : <Menu/>}</button></div>{nav && <div className="border-t border-slate-100 bg-white p-4 lg:hidden"><nav className="grid gap-1">{['Home','About','Features','Opportunities','Institutions','Companies','Contact'].map((x)=><a onClick={() => setNav(false)} key={x} href={x === 'Home' ? '#home' : `#${x.toLowerCase()}`} className="rounded-lg px-3 py-2.5 text-sm font-semibold hover:bg-slate-50">{x}</a>)}<div className="mt-2 grid grid-cols-2 gap-2"><Link to="/login" className="btn-secondary">Log in</Link><Link to="/signup" className="btn-primary">Get started</Link></div></nav></div>}</header>

    <main>
      <section id="home" className="hero-grid relative overflow-hidden bg-gradient-to-b from-blue-50/70 via-white to-white"><div className="absolute -left-40 top-20 h-80 w-80 rounded-full bg-blue-300/20 blur-3xl"/><div className="absolute -right-32 top-10 h-96 w-96 rounded-full bg-violet-300/20 blur-3xl"/><div className="relative mx-auto grid max-w-7xl items-center gap-14 px-4 py-20 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:py-28">
        <div><span className="inline-flex items-center gap-2 rounded-full border border-blue-200 bg-white px-3 py-1.5 text-xs font-bold text-brand-700 shadow-sm"><Sparkles size={14}/>India’s talent-to-opportunity network</span><h1 className="mt-6 max-w-3xl text-4xl font-extrabold leading-[1.08] tracking-[-.045em] text-navy-900 sm:text-5xl lg:text-[64px]">Connecting academia & industry for a <span className="text-gradient">brighter tomorrow.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-500">A unified platform for skill mapping, internships, placements and meaningful industry–academia collaboration.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/signup" className="btn-primary px-6">Get started free<ArrowRight size={17}/></Link><Link to="/opportunities" className="btn-secondary px-6">Explore opportunities</Link><button className="btn-ghost px-5" onClick={() => setDemo(true)}><span className="grid h-7 w-7 place-items-center rounded-full bg-navy-900 text-white"><Play size={12} fill="currentColor"/></span>Watch demo</button></div><div className="mt-8 flex flex-wrap items-center gap-x-6 gap-y-2 text-xs font-semibold text-slate-500">{['Verified institutions','Explainable matches','Built for every learner'].map((x)=><span className="inline-flex items-center gap-1.5" key={x}><CheckCircle2 size={15} className="text-emerald-500"/>{x}</span>)}</div></div>
        <div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-4 rotate-3 rounded-[32px] bg-gradient-to-br from-blue-200/60 to-violet-200/60"/><div className="relative overflow-hidden rounded-[28px] border border-white/80 bg-white p-4 shadow-2xl shadow-blue-900/15"><div className="rounded-2xl bg-navy-900 p-5 text-white"><div className="flex items-center justify-between"><div><p className="text-xs text-blue-200">Career readiness</p><p className="mt-1 text-xl font-bold">Your path to MERN</p></div><span className="grid h-14 w-14 place-items-center rounded-full border-[5px] border-blue-400 text-sm font-extrabold">78%</span></div><div className="mt-5 grid grid-cols-3 gap-2">{[['12','Matches'],['4','Active'],['6','Badges']].map(([v,l])=><div key={l} className="rounded-xl bg-white/10 p-3"><b className="block text-lg">{v}</b><span className="text-[10px] text-blue-200">{l}</span></div>)}</div></div><div className="mt-3 rounded-2xl border border-slate-100 p-4"><div className="flex justify-between"><p className="text-sm font-bold text-navy-900">Recommended for you</p><span className="text-xs font-bold text-emerald-600">92% match</span></div><div className="mt-3 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-600 text-xs font-extrabold text-white">TC</span><div><p className="text-sm font-bold text-navy-900">Frontend Developer Intern</p><p className="text-xs text-slate-400">TCS Digital · Remote</p></div></div><div className="mt-4 h-2 rounded-full bg-slate-100"><div className="h-full w-[92%] rounded-full bg-gradient-to-r from-blue-500 to-emerald-400"/></div></div><div className="mt-3 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-blue-50 p-4"><p className="text-xs font-bold text-blue-600">Strong skills</p><p className="mt-2 text-sm font-bold text-navy-900">React · Git · JS</p></div><div className="rounded-2xl bg-amber-50 p-4"><p className="text-xs font-bold text-amber-600">Next to learn</p><p className="mt-2 text-sm font-bold text-navy-900">Node · MongoDB</p></div></div></div></div>
      </div><div className="mx-auto grid max-w-7xl grid-cols-2 border-y border-slate-200 bg-white px-4 py-8 sm:grid-cols-4 sm:px-6">{[['10K+','Students'],['500+','Institutions'],['1K+','Industry partners'],['5K+','Opportunities']].map(([v,l],i)=><div key={l} className={`text-center ${i>0 ? 'border-l border-slate-200' : ''}`}><strong className="text-2xl font-extrabold text-navy-900 sm:text-3xl">{v}</strong><p className="mt-1 text-xs font-semibold text-slate-400 sm:text-sm">{l}</p></div>)}</div></section>

      <section id="features" className="mx-auto max-w-7xl px-4 py-24 sm:px-6"><div className="mx-auto max-w-2xl text-center"><p className="eyebrow">Why SkillBridge?</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight text-navy-900 sm:text-4xl">One bridge. Every career possibility.</h2><p className="mt-4 leading-7 text-slate-500">Skills become visible, gaps become actionable, and the right opportunities become easier to reach.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{features.map(({icon:Icon,title,text,color})=><div key={title} className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-soft transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-lg"><span className={`grid h-12 w-12 place-items-center rounded-xl ${color}`}><Icon size={23}/></span><h3 className="mt-5 text-lg font-bold text-navy-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-brand-600 opacity-0 transition group-hover:opacity-100">Learn more<ArrowRight size={14}/></span></div>)}</div></section>

      <section id="about" className="bg-navy-900 py-24 text-white"><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-300">How it works</p><h2 className="mt-3 text-3xl font-extrabold sm:text-4xl">From potential to placement, one clear step at a time.</h2><p className="mt-4 leading-7 text-slate-300">A transparent pathway designed to help learners make confident career decisions.</p><Link to="/signup" className="mt-7 inline-flex items-center gap-2 font-bold text-blue-300 hover:text-white">Start your journey<ArrowRight size={17}/></Link></div><div className="space-y-3">{steps.map(([n,title,text],i)=><div key={n} className="group flex gap-4 rounded-2xl border border-white/10 bg-white/[.05] p-4 transition hover:bg-white/[.09]"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blue-500/20 text-xs font-extrabold text-blue-300">{n}</span><div><h3 className="font-bold">{title}</h3><p className="mt-1 text-sm text-slate-400">{text}</p></div>{i<4 && <ArrowRight className="ml-auto hidden self-center text-white/20 sm:block" size={18}/>}</div>)}</div></div></div></section>

      <section className="mx-auto max-w-7xl px-4 py-24 sm:px-6"><div className="grid gap-6 lg:grid-cols-3">{[
        {id:'students',icon:GraduationCap,kicker:'For students',title:'Turn learning into momentum.',text:'Build a rich profile, understand your readiness and apply with confidence.',points:['Personal skill-gap analysis','Role-specific learning paths','Matched jobs and internships'],color:'from-blue-500 to-blue-700'},
        {id:'institutions',icon:Landmark,kicker:'For academia',title:'Make outcomes measurable.',text:'See cohort skills clearly and focus training where students need it most.',points:['Department skill dashboards','Targeted workshop planning','Industry collaboration hub'],color:'from-violet-500 to-indigo-700'},
        {id:'companies',icon:Building2,kicker:'For industry',title:'Find talent by capability.',text:'Reach promising learners and hire using relevant, transparent signals.',points:['Skill-first talent discovery','Candidate match breakdowns','Institution partnerships'],color:'from-emerald-500 to-teal-700'},
      ].map(({id,icon:Icon,kicker,title,text,points,color})=><article id={id} key={id} className="overflow-hidden rounded-3xl border border-slate-200 bg-slate-50"><div className={`h-2 bg-gradient-to-r ${color}`}/><div className="p-7"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white text-brand-600 shadow-sm"><Icon/></span><p className="eyebrow mt-6">{kicker}</p><h3 className="mt-2 text-2xl font-extrabold text-navy-900">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{text}</p><ul className="mt-6 space-y-3">{points.map(x=><li key={x} className="flex items-center gap-2 text-sm font-semibold text-slate-700"><CheckCircle2 size={16} className="text-emerald-500"/>{x}</li>)}</ul></div></article>)}</div></section>

      <section id="opportunities" className="bg-slate-50 py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Live opportunities</p><h2 className="mt-2 text-3xl font-extrabold text-navy-900">Where ambition meets access.</h2></div><Link to="/opportunities" className="btn-secondary">Browse all opportunities<ArrowRight size={16}/></Link></div><div className="mt-10 grid gap-5 md:grid-cols-3">{opportunities.slice(0,3).map((opp)=>{const c=companies.find(x=>x.id===opp.companyId);return <article key={opp.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-soft"><div className="flex items-center gap-3"><span className={`grid h-11 w-11 place-items-center rounded-xl text-xs font-bold text-white ${c?.color}`}>{c?.initials}</span><div><p className="text-xs text-slate-400">{opp.company}</p><h3 className="font-bold text-navy-900">{opp.title}</h3></div></div><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><span className="text-sm font-semibold text-slate-500">{opp.location} · {opp.type}</span><b className="text-sm text-emerald-600">{opp.match}% match</b></div></article>})}</div></div></section>

      <section className="mx-auto max-w-7xl px-4 py-24 sm:px-6"><div className="grid gap-10 lg:grid-cols-2"><div className="rounded-3xl bg-gradient-to-br from-blue-600 to-indigo-700 p-8 text-white sm:p-10"><Quote className="text-blue-200" size={34}/><blockquote className="mt-6 text-xl font-semibold leading-8 sm:text-2xl">“SkillBridge showed me exactly what I needed to learn for frontend roles. Six weeks later, I found an internship that genuinely matched my work.”</blockquote><div className="mt-8 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-full bg-white/20 font-bold">SR</span><div><p className="font-bold">Sneha Reddy</p><p className="text-sm text-blue-200">Frontend Intern · Hyderabad</p></div></div></div><div><p className="eyebrow">Frequently asked</p><h2 className="mt-2 text-3xl font-extrabold text-navy-900">Questions, answered simply.</h2><div className="mt-7 divide-y divide-slate-200 border-y border-slate-200">{faqs.map(([q,a],i)=><div key={q}><button className="flex w-full items-center justify-between gap-4 py-5 text-left font-bold text-navy-900" onClick={()=>setFaq(faq===i?-1:i)}>{q}<ChevronDown size={18} className={`shrink-0 transition ${faq===i?'rotate-180':''}`}/></button>{faq===i&&<p className="pb-5 pr-8 text-sm leading-6 text-slate-500">{a}</p>}</div>)}</div></div></div></section>

      <section className="px-4 pb-24 sm:px-6"><div className="dot-grid relative mx-auto max-w-7xl overflow-hidden rounded-[32px] bg-navy-900 px-6 py-16 text-center text-white sm:px-12"><div className="absolute inset-0 bg-gradient-to-r from-blue-600/30 to-violet-600/30"/><div className="relative"><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-300">Build what comes next</p><h2 className="mx-auto mt-3 max-w-2xl text-3xl font-extrabold sm:text-4xl">Your skills deserve the right opportunity.</h2><p className="mx-auto mt-4 max-w-xl text-slate-300">Join learners, institutions and employers building stronger career pathways together.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/signup" className="btn-primary bg-white text-brand-700 hover:bg-blue-50">Create your free profile<ArrowRight size={16}/></Link><Link to="/login" className="btn-secondary border-white/20 bg-white/10 text-white hover:bg-white/20">Sign in</Link></div></div></div></section>
    </main>

    <footer id="contact" className="border-t border-slate-200 bg-slate-50"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-14 sm:grid-cols-2 sm:px-6 lg:grid-cols-[1.5fr_1fr_1fr_1fr]"><div><Logo/><p className="mt-4 max-w-sm text-sm leading-6 text-slate-500">Building a trusted bridge between academic potential and industry opportunity across India.</p><div className="mt-5 flex gap-2">{[Linkedin,Twitter,Instagram].map((Icon,i)=><button aria-label={['LinkedIn','Twitter','Instagram'][i]} key={i} className="grid h-9 w-9 place-items-center rounded-lg border border-slate-200 bg-white text-slate-500 hover:text-brand-600"><Icon size={16}/></button>)}</div></div>{[['Platform','About','Features','Opportunities','Students'],['Collaborate','Institutions','Companies','Government','Partners'],['Support','Help centre','Privacy','Terms','Contact']].map(([head,...links])=><div key={head}><h3 className="text-sm font-bold text-navy-900">{head}</h3><ul className="mt-4 space-y-3">{links.map(x=><li key={x}><a className="text-sm text-slate-500 hover:text-brand-600" href="#home">{x}</a></li>)}</ul></div>)}</div><div className="border-t border-slate-200 py-5"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-2 px-4 text-xs text-slate-400 sm:flex-row sm:px-6"><p>© 2026 SkillBridge. Frontend demonstration.</p><p>Designed for inclusive career outcomes.</p></div></div></footer>
    <Modal open={demo} onClose={()=>setDemo(false)} title="See SkillBridge in action" description="A quick look at the learner journey."><div className="aspect-video rounded-2xl bg-gradient-to-br from-navy-900 to-blue-800 p-8 text-center text-white"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-white/15"><Play size={26} fill="currentColor"/></span><h3 className="mt-5 text-xl font-bold">Profile → skills → opportunity</h3><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-blue-100">This interactive frontend includes every part of the demo. Choose a role at login to explore the full experience.</p><Link onClick={()=>setDemo(false)} to="/login" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-blue-700">Open demo<ArrowRight size={16}/></Link></div></Modal>
  </div>
}
