import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { Search, MapPin, ArrowRight, SlidersHorizontal } from 'lucide-react'
import { Logo, SkillChip } from '../../components/common/UI'
import { opportunities } from '../../data/opportunities'
import { companies } from '../../data/companies'

export default function PublicOpportunities() {
  const [query,setQuery]=useState(''),[type,setType]=useState('All')
  const filtered=useMemo(()=>opportunities.filter(x=>(type==='All'||x.type===type)&&`${x.title} ${x.company} ${x.skills}`.toLowerCase().includes(query.toLowerCase())),[query,type])
  return <div className="min-h-screen bg-slate-50"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-4 sm:px-6"><Link to="/"><Logo/></Link><div className="flex gap-2"><Link className="btn-ghost hidden sm:flex" to="/login">Log in</Link><Link className="btn-primary" to="/signup">Join SkillBridge<ArrowRight size={16}/></Link></div></div></header><main><section className="bg-navy-900 py-16 text-white"><div className="mx-auto max-w-7xl px-4 sm:px-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-300">Opportunity directory</p><h1 className="mt-3 max-w-2xl text-4xl font-extrabold">Find a role that fits where you’re going.</h1><p className="mt-3 text-slate-300">Explore verified internships and graduate roles from industry partners.</p><div className="relative mt-8 max-w-2xl"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"/><input className="input h-14 pl-12" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search roles, companies or skills"/></div></div></section><section className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2">{['All','Internship','Job'].map(x=><button key={x} onClick={()=>setType(x)} className={type===x?'btn-primary':'btn-secondary'}>{x}</button>)}</div><span className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500"><SlidersHorizontal size={16}/>{filtered.length} opportunities</span></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{filtered.map(opp=>{const c=companies.find(x=>x.id===opp.companyId);return <article key={opp.id} className="card flex flex-col p-5"><div className="flex items-center gap-3"><span className={`grid h-11 w-11 place-items-center rounded-xl text-xs font-bold text-white ${c?.color}`}>{c?.initials}</span><div><p className="text-xs text-slate-400">{opp.company}</p><h2 className="font-bold text-navy-900">{opp.title}</h2></div></div><p className="mt-4 flex items-center gap-1.5 text-sm text-slate-500"><MapPin size={15}/>{opp.location} · {opp.mode}</p><div className="mt-4 flex flex-wrap gap-1.5">{opp.skills.map(x=><SkillChip key={x} tone="slate">{x}</SkillChip>)}</div><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><div><p className="text-sm font-bold text-navy-900">{opp.pay}</p><p className="text-xs text-slate-400">{opp.duration}</p></div><Link to="/login" className="btn-primary">Sign in to apply</Link></div></article>})}</div></section></main></div>
}
